### ISSUE TITLE
Upgrade to Node.js 16

### ISSUE THREAD

**Issue by tommens** [ScaCap/action-surefire-report#113]
When running my workflow that is based on  scacap/action-surefire-report@v1 I get the following warning from GitHub:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the action to use Node.js 16

**Comment by ghaiszaher** [comment]
Hello @tommens, this was already taken care of in https://github.com/ScaCap/action-surefire-report/issues/85 & https://github.com/ScaCap/action-surefire-report/pull/101, [v1](https://github.com/ScaCap/action-surefire-report/tree/v1) is already using Node 16. Do you have a recent example where this warning appears?

**Comment by tommens** [comment]
the problem seems to be solved by upgrading some of my other used actions to a more recent version as well. i guess the warning i received was due to an incompatibility between different actions using different versions of node.js. Thanks for your reactivity you can close this issue.
