### ISSUE TITLE
New release v1.6.0 error loading shared library

### ISSUE THREAD

**Issue by Ajris** [ScaCap/action-surefire-report#140]
Hi, after new release, we have observed an issue:

Run scacap/action-surefire-report@v1
  with:
    check_name: All Tests Result
    github_token: ***
    report_paths: **/surefire-reports/TEST-*.xml, **/failsafe-reports/TEST-*.xml
    create_check: true
    fail_on_test_failures: false
    fail_if_no_tests: true
    skip_publishing: false
    file_name_in_stack_trace: false

node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
``
Error: Error loading shared library libstdc++.so.6: No such file or directory (needed by /__w/_actions/scacap/action-surefire-report/v1/dist/build/Release/xmljs.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:[10] 05:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.1463 (/__w/_actions/scacap/action-surefire-report/v1/dist/index.js:10137:18)
    at __nccwpck_require__ (/__w/_actions/scacap/action-surefire-report/v1/dist/index.js:16797:43)
    at Object.6737 (/__w/_actions/scacap/action-surefire-report/v1/dist/index.js:10091:16)
    at __nccwpck_require__ (/__w/_actions/scacap/action-surefire-report/v1/dist/index.js:16797:43)
    at Object.[12] {
  code: 'ERR_DLOPEN_FAILED'
}
``

**Comment by ghaiszaher** [comment]
@nineinchnick would you know anything about this? I tried the new version internally and didn't face such issues.

**Comment by Ajris** [comment]
For anyone facing the similar issue, changing the version directly to the v1.5.0 solves the problem temporarily :)

**Comment by ghaiszaher** [comment]
@Ajris I reverted the tag v1 to the previous version v1.5.0.

**Comment by ghaiszaher** [comment]
@Ajris could you provide the configuration of the GitHub workflow using this action?

**Comment by nineinchnick** [comment]
Are you using GitHub's or self-hosted runners? Which OS? This was tested only on `ubuntu-latest`.

1.6 switches to using a native library for parsing XML, so it requires some shared libraries in the OS. To mitigate this, we should probably run the action in a container.

**Comment by Ajris** [comment]
We are using github's hosted runners and maven containers.
 
Example job config:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-eclipse-temurin-17-alpine

The configuration of the step:
`
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: ${{ inputs.report-name }}
`

**Comment by ghaiszaher** [comment]
> To mitigate this, we should probably run the action in a container.

I'd like to go with this option, which was also on my list (will also solve https://github.com/ScaCap/action-surefire-report/issues/130). I can spend some time on it in the next few days.

For the time being I'll keep `v1` pointing to `v1.5.0` to not break more workflows, you can still specify `v1.6.0` if it's compatible with your runners.

**Comment by ghaiszaher** [comment]
@Ajris could you verify that `v1` is working again for you now?

**Comment by Ajris** [comment]
V1 is working again. 
I have runned it and it had downloaded the version with this sha: a2d14baac06028516812d93c36cb9c99aa50198e and everything was as before.
 
For us, we have just directly changed it to the v1.5.0 in case of any errors.

**Comment by nineinchnick** [comment]
We are using a container already, aren't we? https://github.com/ScaCap/action-surefire-report/blob/master/action.yml#L52

Specifying `container` on the job level overrides that. I'm trying to find relevant Github docs for that.

**Comment by nineinchnick** [comment]
Ah, it's not a container, just a runtime.

**Comment by ghaiszaher** [comment]
@nineinchnick thanks for the fix.

@Ajris the action should run properly now for tag `v1` or `v1.6.1`. Feel free to reopen if you still face issues.
