### ISSUE TITLE
Error: internal error: Huge input lookup

### ISSUE THREAD

**Issue by thomas0306** [ScaCap/action-surefire-report#145]
My build starts failing since v1.6.0.
![Screenshot 2023-03-10 at 12 16 40](https://user-images.githubusercontent.com/7123240/224304457-b6e5df43-b80d-4b16-9b52-a56ea2d0ecc2.png)

If I point my build specifically to plugin v1.5.0, it is working again
![Screenshot 2023-03-10 at 12 17 23](https://user-images.githubusercontent.com/7123240/224304652-b24e7a25-c597-43d1-8e4d-dcef163c2f5e.png)

I suspect the xml parsing library has been changed since then - https://github.com/ScaCap/action-surefire-report/releases/tag/v1.6.0

Could that be a possibility that the XML_PARSE_HUGE option did not pass properly to the underlying logic of the new library `libxmljs`? - https://github.com/libxmljs/libxmljs/blob/23da4cf9eca569a37cc36a26977fa7ab0b53d875/src/xml_document.cc#L338

**Comment by ghaiszaher** [comment]
Should be solved with https://github.com/ScaCap/action-surefire-report/pull/144

**Comment by ghaiszaher** [comment]
@thomas0306 please try with the new release `v1.6.2` or `v1`

**Comment by thomas0306** [comment]
@ghaiszaher working again with the latest version, many thanks :)
![Screenshot 2023-03-10 at 15 12 38](https://user-images.githubusercontent.com/7123240/224338364-3fe82431-13fb-46aa-a640-c00fdd67a89a.png)
