### ISSUE TITLE
v1.6.1 broke running action on macOS and Windows

### ISSUE THREAD

**Issue by joschi** [ScaCap/action-surefire-report#146]
GitHub Actions of type Docker container only work on Linux.
https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions

The change in [action-surefire-report 1.6.1](https://github.com/ScaCap/action-surefire-report/releases/tag/v1.6.1) broke running in workflows executed on macOS and Windows.

Example: https://github.com/dropwizard/dropwizard/actions/runs/4382796006/jobs/7672260302
```
Run scacap/action-surefire-report@01b27826d208fcb14a8c92a40cb01865c160b825
  with:
    github_token: ***
    check_name: Test Report (windows-latest - Java 17)
    report_paths: **/*-reports/TEST-*.xml
    create_check: true
    fail_on_test_failures: false
    fail_if_no_tests: true
    skip_publishing: false
    file_name_in_stack_trace: false
  env:
    JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.6-10\x6[4](https://github.com/dropwizard/dropwizard/actions/runs/4382796006/jobs/7672260302#step:7:4)
    JAVA_HOME_17_X[6](https://github.com/dropwizard/dropwizard/actions/runs/4382796006/jobs/7672260302#step:7:6)4: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\1[7](https://github.com/dropwizard/dropwizard/actions/runs/4382796006/jobs/7672260302#step:7:7).0.6-[10](https://github.com/dropwizard/dropwizard/actions/runs/4382796006/jobs/7672260302#step:7:10)\x64
Error: Container action is only supported on Linux
```

Refs https://github.com/ScaCap/action-surefire-report/pull/141

**Comment by ghaiszaher** [comment]
@nineinchnick it seems like the new library is causing quite some issues. How about reverting back to Javascript and giving the option to use `libxmljs` over `xml-js` with a new flag?

**Comment by nineinchnick** [comment]
Yes, let's revert this. Sorry about the trouble, I didn't realize all the different use cases. I'll see if I can come up with a portable solution later on.

**Comment by nineinchnick** [comment]
I opened #147 to revert last 3 PRs. Looks like the best way to address memory usage is to directly use `sax-js`, which is what `xml-js` uses anyway.
