### ISSUE TITLE
Fails on `testcase`

### ISSUE THREAD

**Issue by kobrikx** [ScaCap/action-surefire-report#19]
Hello! 
Action fails on parsing junit xml output from Checkov

<img width="586" alt="Снимок экрана 2020-09-10 в 15 21 14" src="https://user-images.githubusercontent.com/24703846/92729501-16f67900-f37b-11ea-961f-d11d98954887.png">

And output is like:
`<?xml version="1.0" ?>
<testsuites failures="7" errors="0" tests="24" disabled="0" time="0.0">
	<testsuite name="Ensure no hard coded AWS access key and and secret key exists in provider" disabled="0" failures="0" errors="0" skipped="0" time="0" tests="3" package="checkov.terraform.checks.provider.aws.credentials">
		<testcase name="terraform Ensure no hard coded AWS access key and and secret key exists in provider aws.default" `

Can you help me with this issue?

Thank you.

**Comment by jmisur** [comment]
Hi can you please attach the entire test xml? Or at least a valid xml chunk?

**Comment by andreacomo** [comment]
I had same problem here: it was caused by the **failsafe maven plugin** that generates an xml summary file. I fixed the problem by changing:
from
```
report_paths: '**/target/*-reports/*.xml'
```

to
```
report_paths: '**/target/*-reports/TEST-*.xml'
```
so I can collect both surefire and failsafe test results.

Hope this can help

**Comment by jmisur** [comment]
Thanks a lot for the tip!
