### ISSUE TITLE
It should be possible to fail the build on test failures

### ISSUE THREAD

**Issue by hennejg** [ScaCap/action-surefire-report#22]
Useful, for example, for CD pipelines where merging a successful branch onto the release source branch doesn't necessarily mean test success for the merge result.

**Comment by poolebu** [comment]
Hello and thankss for this awesome Action! 😄  So I'm not sure if this issues adresses my current problem:

I need my test to fail and show the **failing badge** when it fails. Right now if I use this Action and add the `-Dmaven.test.failure.ignore=true` then when it fails I can see the tests reports (which is, as I said, Awesome! ) BUT all tests show as passing.

Is there something i can do now to get the behaviour I need? Is it related to this PR? 

Thank you!

![2020-10-02_17h32_30](https://user-images.githubusercontent.com/4500001/94941667-845a7d00-04d5-11eb-928f-2b76710eb8a1.png)

**Comment by hennejg** [comment]
The current behavior of this action is that it always returns a successful status to the workflow, independent of the outcome of the tests. This pull request allows you either to
* fail the run at the action if the test outcome wasn't `success` by setting `fail_on_failure: true`
* or to use the test outcome in a later step by providing the output value `outcome`.
However, I am not quite sure whether that addresses your issue. I understand that you see failed tests reported as successful, which would not be something this pull request deals with.

Anyways, you can try to experiment with my release of this action by using `hennejg/github-tag-action@v4.1.jh7`.

**Comment by poolebu** [comment]
Thank you @hennejg , I will give it a try soon. Just to clarify, in your PR, if I set  `fail_on_failure: true`, will I still be able to see the report of the failing tests in the web interface? Or will ir fail and I will have to see the logs of the actions to see which test failed?

**Comment by hennejg** [comment]
Yes, that's the way it is supposed to work. The test report is sent upstream _before_ failing the step. If you experience any problems with the setting, please let me know.

**Comment by jmisur** [comment]
Fixed in #26 
The flag is called `fail_on_test_failures` as it appeared more appropriate to me.
