### ISSUE TITLE
Make no-JUnit test file case as successful case with a warning

### ISSUE THREAD

**Issue by HyukjinKwon** [ScaCap/action-surefire-report#29]
In my case, I dynamically skip and only run  the relevant tests (and therefore don't generate JUnit XML files at all if all are skipped). In this case, the current plugin reports it as a failure (see https://github.com/apache/spark/runs/1196319934 as an example).

```
Result: No test results found!
Posting status 'completed' with conclusion 'failure' to refs/heads/master (sha: 4c712f370e299fe5097bf988107726587ece90fc)
```

Should we maybe issue a warning and make it as a successful case at https://github.com/ScaCap/action-surefire-report/blob/master/action.js#L16, or at least have a way to ignore this error?

**Comment by HyukjinKwon** [comment]
In my case, I worked around by checking if JUnit XML files exist, see also https://github.com/apache/spark/pull/29946. It's not an issue to me anymore.

**Comment by jmisur** [comment]
I think it makes sense to do such a flag. Even Maven does have one to prevent fail if no tests are found.

**Comment by HyukjinKwon** [comment]
Nice, thanks @jmisur. I'm going to use this brand new feature :).
