### ISSUE TITLE
Support for event 'workflow_dispatch'

### ISSUE THREAD

**Issue by pun-ky** [ScaCap/action-surefire-report#48]
I don't see any tab in workflow summary/job summary even if it ends with success :(

I mean... I want to process test results also for workflow run on-demand / not in PR context.

![](https://user-images.githubusercontent.com/10673561/107513681-db214300-6ba8-11eb-8dc4-c2eae9a95182.png)

**Comment by jmisur** [comment]
Hi @pun-ky, there is currently a bug (not sure if with us or github) that the check ends up being in random check suite. Look on the left pane where all suits and checks are shown and "Test Results" should be in one of them.

**Comment by jmisur** [comment]
We're not using workflows. Can you link me to an example?

**Comment by pun-ky** [comment]
I am simply running mvn then copying snippet with action using your step and the tab is not showing up..

https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

Sry but my code is not publicly available / responding via phone 😉

**Comment by jmisur** [comment]
I'm not sure what detailed info you expected, but you'll get failure details when tests fails or errors. Feel free to close if it works.

**Comment by pun-ky** [comment]
even on success, I am expecting to see at least a list of tests being considered.

**Comment by famod** [comment]
@pun-ky just passing by, but it seems you did not really want to close this issue, did you?

**Comment by pun-ky** [comment]
\[1\]

> Hi [**@pun-ky**](https://github.com/pun-ky), there is currently a bug (not sure if with us or github) that the check ends up being in random check suite  
>  

seems that's it. could you provide me a link to be able to track it?

\[2\] 

> even on success, I am expecting to see at least a list of tests being considered.

it's rather a separate issue/feature. as there is absolutely no info which tests are being considered it's kinda black box.

it simply would be nice to have an option to turn it on to be able to list tests being considered and after assuring if it's ok then disabling it.
