### ISSUE TITLE
Feature request - Ability to skip publishing report

### ISSUE THREAD

**Issue by devinrsmith** [ScaCap/action-surefire-report#57]
I've got a use case that is somewhat related to #31 - I'm uploading the xml artifacts from one job, and having action-surefire-report publish them from another job (due to workflow security).

That said, I'd *like* the first job to fail if there are any failures in the xml artifacts. I think it could be an interesting use case for action-surefire-report to have an option `skip_publishing`; setting `skip_publishing` and `fail_on_test_failures` to true would achieve what I'm hoping to accomplish.

Let me know if you think this would be useful.

**Comment by jmisur** [comment]
I actually named it skip_publishing since it's a better business term. It's on master now and will reach v1 soon.
