### ISSUE TITLE
Add option to skip publishing in case all tests were green

### ISSUE THREAD

**Issue by kwin** [ScaCap/action-surefire-report#72]
In case no test failure was detected it should be possible to optionally skip generating the report as it doesn't contain relevant information.

**Comment by jmisur** [comment]
I don't think this is a good idea, because you will not know when the tests or the report publishing failed vs. when it run and didn't publish anything because of this flag. Why not having it there all the time.

**Comment by kwin** [comment]
In case of matrix builds with both ITs and UTs you can easily have 20 or more reports. To ease selection of the one containing of the failures it should be possible to optionally prevent creation of all other ones. 

Regarding
> when the tests or the report publishing failed 

I expect the GitHub action to fail in that case!
