### ISSUE TITLE
Cannot read property 'skipped' of undefined

### ISSUE THREAD

**Issue by michaelcoll** [ScaCap/action-surefire-report#8]
Hi,

During the build of my project I have this error : `##[error]Cannot read property 'skipped' of undefined`

Do you any clue on the problem ?

Thanks.

**Comment by djcsdy** [comment]
This problem is almost certainly caused by an XML test report that does not contain any `<testcase>` elements.

The problematic line of code is here: https://github.com/ScaCap/action-surefire-report/blob/dec13d8b948a999c37d512123d1eb0e2d0629725/utils.js#L39

**Comment by jmisur** [comment]
Discussion on #9 hints that this works on master.

**Comment by michaelcoll** [comment]
Indeed, using 1.0.3 fixed the problem. Thanks.
