### ISSUE TITLE
No tests found when gradle cache entry is used

### ISSUE THREAD

**Issue by huehnerlady** [ScaCap/action-surefire-report#80]
We are using gradle as a build tool. For our CI Setup we use GitHub actions and that includes this one, which generally we like.

Unfortunately now we ran into the issue for the first time, that the action reported a failure because there were no tests found. I like that feature, because it actually prevented me disabling all test by accident once. But in this case we used a gradle cache and so we expected that there might not be any tests.

Any idea how we can accommodate that without disabling the check of missing tests?

**Comment by jmisur** [comment]
Do you know how can gradle "publish" the information that you're using cache for tests (whatever that means, I don't have experience in that regard) so that the action can use it to disable no-tests check?

**Comment by huehnerlady** [comment]
Many thanks for your quick reply and sorry for the late answer.

I cannot reproduce the error anymore, so I would close the issue for now and would create one with more information once that happens again
