### ISSUE TITLE
Annotation shows wrong class path on multi-module project

### ISSUE THREAD

**Issue by leonarta** [ScaCap/action-surefire-report#84]
I work on a large multi-module Maven project. In some cases, a given class and method name are used in more than one module.

We've begun using this action for our JUnit 4 test reporting quite effectively, but recently ran across a case where the annotation for a unit test failure reported the _wrong_ class path:

![image](https://user-images.githubusercontent.com/1641628/167875047-fb699bb4-3a71-47be-9a0a-aa129b2fbec5.png)

The first line of annotation reported that the error occurred in the `azure` module, but if you download the logs or even just click on the "Raw output" button in the annotation you can see the error was actually in the `mq` module.

Each of these modules _does_ have a `WorkProviderTest.messageToTask` method.  The log and raw output correctly report which one had the failure, but the first line of the annotation gets it wrong.

**Comment by yeikel** [comment]
I believe that https://github.com/ScaCap/action-surefire-report/pull/61 should take of this

**Comment by ghaiszaher** [comment]
With #61 the annotation should be shown in the correct file now when package names are different. 
Feel free to reopen if you still face the issue.
