### ISSUE TITLE
Update to actions/core@v1.10.0

### ISSUE THREAD

**Issue by mrmeyers99** [ScaCap/action-surefire-report#94]
We are getting warnings when using this action that the set-output commands via standard out have been deprecated.  [The release note](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) makes it sound like for actions using actions/core, the only action required is to update to `v1.10.0`.

**Comment by renatoabreu11** [comment]
The package actions/core was updated to the latest version with https://github.com/ScaCap/action-surefire-report/pull/101. A marketplace release will come shortly.

Thanks for the heads-up and sorry for the delay!
