### ISSUE TITLE
This repo appears to have been abandoned

### ISSUE THREAD

**Issue by pdehlke** [ScaCap/action-surefire-report#98]
There hasn't been a push or merge in well over a year.

Critical issues like #85 and #94 have languished.

Please do the decent thing and archive the repo, as an indicator to others that they shouldn't get their hopes up. Several recently updated forks are available.

**Comment by renatoabreu11** [comment]
Hey @pdehlke,

We apologize for the lack of maintenance and we will try to do better henceforth. 
Regarding the PRs you've mentioned, the issues have been tackled and the respective releases were published to the marketplace. Furthermore, all the security vulnerabilities are now fixed.
